no change     /home1/04637/mdl2665/anaconda3/condabin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda
no change     /home1/04637/mdl2665/anaconda3/bin/conda-env
no change     /home1/04637/mdl2665/anaconda3/bin/activate
no change     /home1/04637/mdl2665/anaconda3/bin/deactivate
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.sh
no change     /home1/04637/mdl2665/anaconda3/etc/fish/conf.d/conda.fish
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/Conda.psm1
no change     /home1/04637/mdl2665/anaconda3/shell/condabin/conda-hook.ps1
no change     /home1/04637/mdl2665/anaconda3/lib/python3.9/site-packages/xontrib/conda.xsh
no change     /home1/04637/mdl2665/anaconda3/etc/profile.d/conda.csh
no change     /home1/04637/mdl2665/.bashrc
No action taken.

     active environment : fenicsx-env
    active env location : /home1/04637/mdl2665/anaconda3/envs/fenicsx-env
            shell level : 2
       user config file : /home1/04637/mdl2665/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home1/04637/mdl2665/anaconda3  (writable)
      conda av data dir : /home1/04637/mdl2665/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home1/04637/mdl2665/anaconda3/pkgs
                          /home1/04637/mdl2665/.conda/pkgs
       envs directories : /home1/04637/mdl2665/anaconda3/envs
                          /home1/04637/mdl2665/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Linux/4.18.0-372.26.1.el8_6.x86_64 rocky/8.6 glibc/2.28
                UID:GID : 839365:819760
             netrc file : None
           offline mode : False

TACC:  Starting up job 564629 
TACC:  Starting parallel tasks... 
srun: got SIGCONT
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 564629 ON c312-022 CANCELLED AT 2022-11-23T10:39:02 ***
srun: forcing job termination
slurmstepd: error: *** STEP 564629.0 ON c312-022 CANCELLED AT 2022-11-23T10:39:02 ***

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 100327 RUNNING AT c314-204
=   EXIT CODE: 15
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
[proxy:0:0@c312-022.ls6.tacc.utexas.edu] HYD_pmcd_pmip_control_cmd_cb (pm/pmiserv/pmip_cb.c:899): assert (!closed) failed
[proxy:0:0@c312-022.ls6.tacc.utexas.edu] HYDT_dmxu_poll_wait_for_event (tools/demux/demux_poll.c:76): callback returned error status
[proxy:0:0@c312-022.ls6.tacc.utexas.edu] main (pm/pmiserv/pmip.c:169): demux engine error waiting for event
srun: error: c312-022: task 0: Exited with exit code 7
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Terminated (signal 15)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
